---
README.md:
    name: "doctrine-extensions"
    minor_version: "0.1"
    badges:
        - "[![Dependency Status](https://www.versioneye.com/user/projects/53dde6ea8e78abc19100003a/badge.svg)](https://www.versioneye.com/user/projects/53dde6ea8e78abc19100003a)"
        - "[![Build Status](http://drone.etna-alternance.net/github.com/etna-alternance/composer-doctrine-extensions/status.svg?branch=master)](http://drone.etna-alternance.net/github.com/etna-alternance/composer-doctrine-extensions)"
        - "[![Coverage Status](https://coveralls.io/repos/etna-alternance/composer-doctrine-extensions/badge.png?branch=master)](https://coveralls.io/r/etna-alternance/composer-doctrine-extensions?branch=master)"
        - "[![Scrutinizer Code Quality](https://scrutinizer-ci.com/g/etna-alternance/composer-doctrine-extensions/badges/quality-score.png?b=master)](https://scrutinizer-ci.com/g/etna-alternance/composer-doctrine-extensions/?branch=master)"
